### PR TITLE
Issue #22 enum anno evo

### PR DESCRIPTION
**Pull request by turbomam**
- Switch to poetry
- check in some enum annotation and curation code that was developed elsewhere

I have moved the previou setup.py-oriented files including the Makefile to `./pre_poetry`

There is a nested loop over the same iterable (`requested_pvs_names`) in `linkml_model_enrichment/annotators/enum_annotator.py` that has to be dealt with

### CODE REVIEW

**Comment by turbomam** [comment]
Fails GH actions checks because that requires the `requirements.txt`. How to move the GH actions to poetry? Will work on that.

**Comment by turbomam** [comment]
tried testing within poetry:

```shell
poetry run pytest
```

> ======================================================================================== test session starts =========================================================================================
platform darwin -- Python 3.9.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/MAM/Documents/gitrepos/linkml-model-enrichment
collected 17 items / 1 error / 16 selected                                                                                                                                                           

> =============================================================================================== ERRORS ===============================================================================================
__________________________________________________________________________ ERROR collecting tests/test_combined_tsv_enum.py __________________________________________________________________________
ImportError while importing test module '/Users/MAM/Documents/gitrepos/linkml-model-enrichment/tests/test_combined_tsv_enum.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_combined_tsv_enum.py:9: in <module>
    from linkml_model_enrichment.annotators.enum_annotator import all_enums_to_ols
E   ImportError: cannot import name 'all_enums_to_ols' from 'linkml_model_enrichment.annotators.enum_annotator' (/Users/MAM/Documents/gitrepos/linkml-model-enrichment/linkml_model_enrichment/annotators/enum_annotator.py)
========================================================================================== warnings summary ==========================================================================================
../../../Library/Caches/pypoetry/virtualenvs/linkml-model-enrichment-ni1l8Qyw-py3.9/lib/python3.9/site-packages/rdflib_jsonld/__init__.py:9
  /Users/MAM/Library/Caches/pypoetry/virtualenvs/linkml-model-enrichment-ni1l8Qyw-py3.9/lib/python3.9/site-packages/rdflib_jsonld/__init__.py:9: DeprecationWarning: The rdflib-jsonld package has been integrated into rdflib as of rdflib==6.0.0.  Please remove rdflib-jsonld from your project's dependencies.
    warnings.warn(

> ../../../Library/Caches/pypoetry/virtualenvs/linkml-model-enrichment-ni1l8Qyw-py3.9/lib/python3.9/site-packages/funowl/base/cast_function.py:2
  /Users/MAM/Library/Caches/pypoetry/virtualenvs/linkml-model-enrichment-ni1l8Qyw-py3.9/lib/python3.9/site-packages/funowl/base/cast_function.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    from collections import Iterable, UserList

> -- Docs: https://docs.pytest.org/en/stable/warnings.html
====================================================================================== short test summary info =======================================================================================
ERROR tests/test_combined_tsv_enum.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================================================== 2 warnings, 1 error in 2.69s ====================================================================================
MAM@MAM-M74 linkml-model-enrichment %

**Review by cmungall — APPROVED** [review]
As per http://berkeleybop.org/best_practice it's best to not mix concerns in one PR...

...however for a repo like this one that is still a bit experimental I think sometimes mega PRs are OK and even desirable...

**Review by cmungall — COMMENTED** [review]
given the size of this I would rather merge earlier then tweak rather than having a long running large PR

I believe teh test fails are a known issue

**Review by cmungall — APPROVED** [review]
I recommend separate PRs for separate concerns - poetry should go in its own PR

however, ok to merge this

**Pull request merged**
